### ISSUE TITLE
Missing files for Ghutalyn

### ISSUE THREAD

**Issue by chron0** [zezic/nextgen_skins#1]
Ahoy there,

thanks for making and releasing your awesome mixxx skins. I was trying the early version of ghutalyn and saw your screenshot in the forums: http://zezic.ru/mixxx/IMG_61172.jpg

Is there any chance you could upload that work into this or another GH repo (even if it isn't "ready" yet) so that we can start downloading and playing with it as well? From all available skins IMHO ghutalyn is one of the most usable and eye-candy skins ATM :) Thanks a lot in advance.

**Comment by chron0** [comment]
ping

**Comment by zezic** [comment]
pong! Sorry for late reply.
I can share [this](http://zezic.ru/mixxx/IMG_61172.jpg) skin soon, of course when i'm reach my main PC (about 1 or 2 days).

**Comment by chron0** [comment]
Ah, sweet, yes, that is exactly the one I was looking for, which seems like a very well rounded upgrade to the already awesome Ghutalyn skin. I've been using Ghutalyn ever since I've found it and I am very happy with it. 

No worries about the lag, I've done my fair share of UIs on my own and am well aware of the time, skill and effort it takes, to produce something on this level of quality, eye-candy and usability. IMHO there are still a lot of people out there who believe that free, open-source and individual/p2p-community (as opposed to industrial/corporational) produced software and systems are inferior to expensive proprietary alternatives. Then you show them things like Mixxx with Ghutalyn there's always: "Whooa, I didn't even knew..." that goes to show, hey, that isn't really so.

So sharing is caring, thanks for caring, because if the files are online and available, those who just want to use the skin, can just download it, and those who want to play and learn can take the sources and mash up their own stuff, according to their personal needs and we enrich everybody with more available great skins.

**Comment by chron0** [comment]
Ping :) Did you happen to get to your PC in the meantime? I haven't seen any update here, maybe your released it somewhere else?

**Comment by zezic** [comment]
Ohh! Sorry! Completely forgot about your request there!
Gudron adapted to Mixxx 2.0 released here: http://zezic.ru/mixxx/files/Gudron.zip as part of GSoC 2016 proposal http://zezic.ru/mixxx
Skin lacks support of effects and vinyl settings but should work fine.
