### ISSUE TITLE
Mockups From Gudron Thread

### ISSUE THREAD

**Issue by alhadebe** [zezic/nextgen_skins#2]
@zezic 
Hi there mate.
I was looking into starting a Mixx skin and saw some of your mockups [https://imgur.com/a/EUPCQHf](url) from the gudron thread on the mixxx forums.

Would you be ok to share some of that work if you started or the source SVG.

Some great/amazing ideas from you and was hoping to use them as inspiration.

 Regards

**Comment by alhadebe** [comment]
ping

**Comment by zezic** [comment]
@NotYourAverageAl pong!
Hi. I would like to continue my work sooner or later and implement the actual skin which will be based on these mockups. I hope for your understanding!

**Comment by alhadebe** [comment]
@zezic 
Can't wait to see what you'll do with it.
 
Cheers
